# -*- coding: utf-8 -*-
"""Copy of Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7TN5zqjwGq4ieRWZ577vaeU3wq38mV-

in this part we want to preprocess data that crawl from divar website. beacuase there are nonvalid value should be removed
"""

import pandas as pd
# dade combined_csv.csv dar file divar_crawler mojode ke hasl jam avari dade haye divare
data = pd.read_csv('/content/combined_csv.csv')
data

type(data)

# SOME VALID VALUE WE SEE DOR EACH COLUMN IN DIVAR THAT OUR DATA SHOULD HAVE IT IN EACH COLUMN...

body=['بدون رنگ','چند لکه رنگ','دو لکه رنگ','یک لکه رنگ']
gear=['اتوماتیک','دنده‌ای']
color=['آبی','آلبالویی','اطلسی','بادمجانی','برنز','بژ','بنفش','پوست‌پیازی','تیتانیوم','خاکستری','خاکی','دلفینی','ذغالی','زرد','زرشکی','زیتونی','سبز','سربی','سرمه‌ای','سفید','سفید صدفی','طلایی','طوسی','عدسی','عنابی','قرمز','قهوه‌ای','کربن‌بلک','کرم','گیلاسی','مسی','مشکی','موکا','نارنجی','نقرآبی','نقره‌ای','نوک‌مدادی','یشمی']
year =['۱۹۸۷ - ۱۳۶۶','۱۹۸۸ - ۱۳۶۷','۱۹۸۹ - ۱۳۶۸','۱۹۹۰ - ۱۳۶۹','۱۹۹۱ - ۱۳۷۰','۱۹۹۲ - ۱۳۷۱','۱۹۹۳ - ۱۳۷۲','۱۹۹۴ - ۱۳۷۳','۱۹۹۵ - ۱۳۷۴','۱۹۹۶ - ۱۳۷۵','۱۹۹۷ - ۱۳۷۶','۱۹۹۸ - ۱۳۷۷','۱۹۹۹ - ۱۳۷۸','۲۰۰۰ - ۱۳۷۹','۲۰۰۱ - ۱۳۸۰','۲۰۰۲ - ۱۳۸۱','۲۰۰۳ - ۱۳۸۲','۲۰۰۴ - ۱۳۸۳','۲۰۰۵ - ۱۳۸۴','۲۰۰۶ - ۱۳۸۵','۲۰۰۷ - ۱۳۸۶','۲۰۰۸ - ۱۳۸۷','۲۰۰۹ - ۱۳۸۸','۲۰۱۰ - ۱۳۸۹','۲۰۱۱ - ۱۳۹۰','۲۰۱۲ - ۱۳۹۱','۲۰۱۳ - ۱۳۹۲','۲۰۱۴ - ۱۳۹۳','۲۰۱۵ - ۱۳۹۴','۲۰۱۶ - ۱۳۹۵','۲۰۱۷ - ۱۳۹۶','۲۰۱۸ - ۱۳۹۷','۲۰۱۹ - ۱۳۹۸']

# THIS PART CONVER PERSIAN NUMBER TO ENGLISH
import re
def convert_fa_numbers(input_str):
    """
    This function convert Persian numbers to English numbers.
    
    Keyword arguments:
    input_str -- It should be string
    Returns: English numbers
    """
    mapping = {
        '۰': '0',
        '۱': '1',
        '۲': '2',
        '۳': '3',
        '۴': '4',
        '۵': '5',
        '۶': '6',
        '۷': '7',
        '۸': '8',
        '۹': '9',
        '.': '.',
    }
    return _multiple_replace(mapping, input_str)

def _multiple_replace(mapping, text):
    """
    Internal function for replace all mapping keys for a input string
    :param mapping: replacing mapping keys
    :param text: user input string
    :return: New string with converted mapping keys to values
    """
    pattern = "|".join(map(re.escape, mapping.keys()))
    return re.sub(pattern, lambda m: mapping[m.group()], str(text))

"""DAR BAKHS ZIR BAYAD CHECK KONIM KE SOTON HA 
DARAYE MAGHADIR MONASEB BASHAND VA MAGHADIR NAMALOOM NADASHTE BASHAND.
HAMCHENIN BAYAD MAGHADIR FARSI RA HAZF KONIM.
TABDIL BE ENGLISH KONIM.
VA DAR AKHAR TARIKH RA SHAMSI DARA NAZAR MIGIRIM VA NORMAL MIKONIM.
"""

# should check value of each column
data = data.dropna()
data = data.drop(data[~data['gear'].isin(gear)].index)
data = data.drop(data[~data['body'].isin(body)].index)
data = data.drop(data[~data['color'].isin(color)].index)
data = data.drop(data[~data['year'].isin(year)].index)

# preprocess data and remove word like 'تومان' and convert persian number to english

data['price'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
data['price'] = data['price'].apply(convert_fa_numbers)
data['price'] = pd.to_numeric(data['price'])
# convert persian to english

data['usage'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
data['usage'] = data['usage'].apply(convert_fa_numbers)
data['usage'] = pd.to_numeric(data['usage'])
data = data.dropna()

data['year'] = data['year'].str[-4:]
data['year'] = data['year'].apply(convert_fa_numbers)
data = data.dropna()

data.to_csv('/content/final_result.csv',index=False,header=True)
data